# Generated by Django 2.2.16 on 2022-04-30 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220429_1625'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review_author',
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Минимальная оценка 1'), django.core.validators.MaxValueValidator(limit_value=10, message='Максимальная оценка 10')], verbose_name='Оценка произведения'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='unique_review_author'),
        ),
    ]
